#
# Starts local development version of Geth
#

version: '3'
services:
  rinkeby:
    image: ethereum/client-go
    container_name: geth
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
      - "30303:30303"
    command: >-
      --dev
      --datadir=~/.ethereum
      --rpc --rpcaddr=0.0.0.0 --rpcvhosts="*" --rpccorsdomain="*" --rpcapi "db,personal,eth,net,web3"
      --ws --wsaddr=0.0.0.0 --wsorigins="*"
      --graphql --graphql.addr=0.0.0.0 --graphql.vhosts="*" --graphql.corsdomain="*"
      --nousb
    volumes:
      - ./run/chain:/root/.ethereum
